version: "3"

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: .env

  bot:
    build: .
    env_file: .env
    depends_on:
      - db
      - redis
      - lavalink
    links:
      - db:postgres
      - redis:redis
      - lavalink:lavalink
    volumes:
      - ./:/code

  redis:
    image: redis:alpine
    restart: always

  lavalink:
    image: samrid/ready-lavalink

volumes:
  postgres-data: