[tool.poetry]
name = "hikari-bot"
version = "0.1.0"
description = "A bot written in python's hikari and tanjun module that implements slash commands"
authors = ["Nishant Sapkota <snishant306@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.10"
hikari = {git = "https://github.com/FasterSpeeding/hikari", rev = "task/components"}
uvloop = "^0.16.0"
python-dotenv = "^0.19.0"
aiohttp = "^3.7.4"
hikari-tanjun = {git = "https://github.com/FasterSpeeding/Tanjun", rev = "task/components"}

[tool.poetry.dev-dependencies]
black = "^21.8b0"
isort = "^5.9.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
